# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Артем\cw-1-course\IOMH.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        StyleSheet_Button = '''
        QPushButton {                                         /* #Button */
            background-color: rgb( 43, 153, 91 );
            padding-left: 4px;
            padding-right: 4px;
            padding-top: 1px;
            padding-bottom: 1px;
            text-decoration:none;
            text-align:center;
            margin:5px 0;
            display: block;
            font: 15px tahoma;
            border: 1px solid rgb( 33, 126, 74 );
            color:#fff;
        }
        QPushButton:hover {
            background-color: rgb( 75, 183, 141 );
            transition: 5 ms;
        } 
        '''
        StyleSheet_Button2 = '''
                QPushButton {                                         /* #Button */
                    background-color: rgb( 43, 153, 91 );
                    padding-left: 5px;
                    padding-right: 5px;
                    padding-top: 2px;
                    padding-bottom: 2px;
                    text-decoration:none;
                    text-align:center;
                    margin:5px 0;
                    display: block;
                    font: 20px tahoma;
                    border: 1px solid rgb( 33, 126, 74 );
                    color:#fff;
                }
                QPushButton:hover {
                    background-color: rgb( 75, 183, 141 );
                    transition: 5 ms;
                } 
                '''
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #6b97e7;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, 5, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(430, 10, 361, 531))
        self.textBrowser.setStyleSheet("background-color: white; border: 2px solid red; border-radius: 4px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 150, 401, 87))
        self.textEdit.setStyleSheet("background-color: white; border: 2px solid red; border-radius: 4px;")
        self.textEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit.setLineWrapColumnOrWidth(0)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 250, 100, 35))
        self.pushButton.setStyleSheet(StyleSheet_Button)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 390, 180, 70))
        self.pushButton_2.setStyleSheet(StyleSheet_Button2)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setStyleSheet("color: white")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setStyleSheet("background-color: #6b97e7")
        self.menu.setObjectName("menu")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu_3 = QtWidgets.QMenu(self.menu)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.menu_3.addAction(self.action_9)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_10)
        self.menu_3.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_3.menuAction())
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MashaHelper"))
        MainWindow.setWindowIcon(QtGui.QIcon('masha.png'))
        self.label.setText(_translate("MainWindow", "Маша"))
        self.label_2.setText(_translate("MainWindow", "Пишите здесь:"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.pushButton_2.setText(_translate("MainWindow", "Говорите"))
        self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.action_5.setText(_translate("MainWindow", "О разработчиках"))
        self.menu_3.setTitle(_translate("MainWindow", "О программе"))
        self.action_3.setText(_translate("MainWindow", " ЕЩЕ"))
        self.action_4.setText(_translate("MainWindow", "паи"))
        self.action_9.setText(_translate("MainWindow", "Список команд"))
        self.action_10.setText(_translate("MainWindow", "Инструкция пользователя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

